services:
  mongodb:
    image: mongo:latest
    container_name: grandstay-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: grandstay_hotel
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
